apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: cynicdog/vertx-quarkus-react:v1.0
          ports:
            - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 3030
      targetPort: 3030
  selector:
    app: react-app